# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('num_of_ques', models.IntegerField()),
                ('num_of_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemsOnAges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('num_of_ques', models.IntegerField()),
                ('num_of_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progressions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('num_of_ques', models.IntegerField()),
                ('num_of_points', models.IntegerField()),
            ],
        ),
    ]
