# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0002_numbers_problemsonages_progressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulae',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
        migrations.AddField(
            model_name='problemsonages',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
        migrations.AddField(
            model_name='progressions',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
    ]
